### ISSUE TITLE
not all arguments converted during string formatting

### ISSUE THREAD

**Issue by txsastre** [NAUbackup/VmBackup#10]
When trying to backup, manually or via config-file: 

 *** vm-export begin <machine>
not all arguments converted during string formatting.
2015-04-13-(13:18:42) - *** vm-export begin<machine>
not all arguments converted during string formatting
2015-04-13-(13:18:42) - ***ERROR EXCEPTION - exceptions.TypeError
2015-04-13-(13:18:42) - ***ERROR NOTE: see VmBackup output for details
Traceback (most recent call last):
  File "./VmBackup.py", line 707, in ?
    main(session)
  File "./VmBackup.py", line 153, in main
    backup_dir = get_backup_dir(vm_backup_dir)
  File "./VmBackup.py", line 389, in get_backup_dir
    backup_dir = BACKUP_DIR_PATTERN \
TypeError: not all arguments converted during string formatting

I've revised the python code, as I'm not to much into python, but I cannot see nothing wrong there.

**Comment by txsastre** [comment]
Well, I was NAS problem.
as says in "vmBackup.py" line 39 
# note - some NAS file servers may fail with ':', so change to your desired format
so I changed the patterns removing ':' and it works.
