### ISSUE TITLE
VmBackup.py: script doesn't work for me. Could You help, please

### ISSUE THREAD

**Issue by Burzump** [NAUbackup/VmBackup#59]
Hi! Could someone help, please? What's wrong? Script doesn't work for me. No complite backup, no log in file.
Xenserver 7.0
VmBackup.py 3.22
Python 2.7.13

[root@Xen03 NAUbackup]# ./VmBackup.py XXXXXXXXXX OTRS preview
2017-11-15-(14:54:26) - VmBackup config loaded from: OTRS
2017-11-15-(14:54:26) - VmBackup.py running with these settings:
2017-11-15-(14:54:26) -   backup_dir        = /snapshots/BACKUPS
2017-11-15-(14:54:26) -   status_log        = /snapshots/NAUbackup/status.log
2017-11-15-(14:54:26) -   compress          = False
2017-11-15-(14:54:26) -   max_backups       = 2
2017-11-15-(14:54:26) -   vdi_export_format = raw
2017-11-15-(14:54:26) -   pool_db_backup    = 0
2017-11-15-(14:54:26) -   exclude (cnt)= 0
2017-11-15-(14:54:26) -   exclude: 
2017-11-15-(14:54:26) -   vdi-export (cnt)= 0
2017-11-15-(14:54:26) -   vdi-export: 
2017-11-15-(14:54:26) -   vm-export (cnt)= 1
2017-11-15-(14:54:26) -   vm-export: OTRS
Traceback (most recent call last):
  File "./VmBackup.py", line 1453, in <module>
    session.xenapi.login_with_password(username, password)
  File "/snapshots/NAUbackup/XenAPI.py", line 248, in __call__
    return self.__send(self.__name, args)
  File "/snapshots/NAUbackup/XenAPI.py", line 141, in xenapi_request
    self._login(methodname, params)
  File "/snapshots/NAUbackup/XenAPI.py", line 165, in _login
    result = _parse_result(getattr(self, 'session.%s' % method)(*params))
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1301, in single_request
    self.send_content(h, request_body)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1448, in send_content
    connection.endheaders(request_body)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1236, in connect
    server_hostname=sni_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 833, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
[root@Xen03 NAUbackup]#

**Comment by thomasmck** [comment]
Try changing `session = XenAPI.Session('https://localhost/')` on line 1452 to `session = XenAPI.Session('https://localhost/', ignore_ssl=True)` and see if that fixes it.

**Comment by Burzump** [comment]
Now get this:

Traceback (most recent call last):
  File "./VmBackup.py", line 1452, in <module>
    session = XenAPI.Session('https://localhost/', ignore_ssl=True)
TypeError: __init__() got an unexpected keyword argument 'ignore_ssl

**Comment by thomasmck** [comment]
Where did you get your version of XenAPI.py from? Can you try again with the XS 7.2 SDK version (They are backwards compatible) from https://www.citrix.com/downloads/xenserver/product-software/xenserver-72-standard-edition.html

**Comment by Burzump** [comment]
Now use XenAPI.py from XS 7.2 SDK and get:
 
[root@Xen03 NAUbackup]# ./VmBackup.py XXXXXXXXXX OTRS preview
2017-11-15-(16:02:19) - VmBackup config loaded from: OTRS
2017-11-15-(16:02:19) - VmBackup.py running with these settings:
2017-11-15-(16:02:19) -   backup_dir        = /snapshots/BACKUPS
2017-11-15-(16:02:19) -   status_log        = /snapshots/NAUbackup/status.log
2017-11-15-(16:02:19) -   compress          = False
2017-11-15-(16:02:19) -   max_backups       = 2
2017-11-15-(16:02:19) -   vdi_export_format = raw
2017-11-15-(16:02:19) -   pool_db_backup    = 0
2017-11-15-(16:02:19) -   exclude (cnt)= 0
2017-11-15-(16:02:19) -   exclude: 
2017-11-15-(16:02:19) -   vdi-export (cnt)= 0
2017-11-15-(16:02:19) -   vdi-export: 
2017-11-15-(16:02:19) -   vm-export (cnt)= 1
2017-11-15-(16:02:19) -   vm-export: OTRS
Traceback (most recent call last):
  File "./VmBackup.py", line 1452, in <module>
    session = XenAPI.Session('https://localhost/', ignore_ssl=True)
  File "/snapshots/NAUbackup/XenAPI.py", line 136, in __init__
    verbose, allow_none, context=ctx)
TypeError: __init__() got an unexpected keyword argument 'context'
[root@Xen03 NAUbackup]#

If delete ignore_ssl=True from VmBackup.py, get at the end:

Traceback (most recent call last):
  File "./VmBackup.py", line 1453, in <module>
    session.xenapi.login_with_password(username, password)
  File "/snapshots/NAUbackup/XenAPI.py", line 262, in __call__
    return self.__send(self.__name, args)
  File "/snapshots/NAUbackup/XenAPI.py", line 149, in xenapi_request
    self._login(methodname, params)
  File "/snapshots/NAUbackup/XenAPI.py", line 186, in _login
    raise e
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
[root@Xen03 NAUbackup]#

**Comment by thomasmck** [comment]
ok well I'm fairly certain that the ignore_ssl=True part is needed to fix your original error (see https://github.com/xapi-project/xen-api/issues/2100). From looking in XenAPI.py on line 136 we are calling the xmlrpclib. If that is not expecting the context argument then I imagine you are not using the correct version.

Looking at the xmlrpclib package page (https://docs.python.org/2/library/xmlrpclib.html) it looks like the context parameter was added in version 2.7.9 ("Changed in version 2.7.9: Added the context argument") so you will need to update to at least this version.

**Comment by Burzump** [comment]
Ok. Will try to downgrade Python to 2.7.9 version. At now use Python 2.7.13.
Thanks, thomasmck!

**Comment by NAUbackup** [comment]
Thanks for your help on this, @thomasmck ... I will try to take a look soon to see what version of XenApi.py and python I am running for comparison.
--Tobias

**Comment by styk-tv** [comment]
So it actually works if you overwrite ssl settings before making the call, like this
```
        import ssl
        ssl._create_default_https_context = ssl._create_unverified_context
        self._xenSession = XenAPI.Session(self._dataXen.api_url)
```

3rd line is my session code, yours will be different.

**Comment by gfiasco** [comment]
change line 


```python
        session = XenAPI.Session('https://localhost/')
```

to  
```python
      session = XenAPI.Session('http://localhost/')
```

**Comment by dangbird** [comment]
@gfiasco Thanks for this change, it worked for me.  No issues with XenServer 7.6 but Version 8.0 that was just released threw this error:
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579) 
changing to http://localhost from https allows the backup to run. 

May need to add code to check version and switch from https to http or someone likely much smarter can advise a solution.

**Comment by NAUbackup** [comment]
I just released V3.24 and would be interested if this error still occurs. Thanks!

**Comment by sniperkitten** [comment]
Hello!

Faced same issue today with Xen Server 8 and latest NAUbackup+XenAPI.py
Changing to http worked for me also: XenAPI.Session('http://localhost/')

Error messages:
`Traceback (most recent call last):
  File "/snapshots/NAUbackup/VmBackup.py", line 1616, in <module>
    session.xenapi.login_with_password(username, password)
  File "/snapshots/NAUbackup/XenAPI.py", line 264, in __call__
    return self.__send(self.__name, args)
  File "/snapshots/NAUbackup/XenAPI.py", line 151, in xenapi_request
    self._login(methodname, params)
  File "/snapshots/NAUbackup/XenAPI.py", line 188, in _login
    raise e
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)`

Regards

**Comment by NAUbackup** [comment]
Sorry to hear that. I will take a look, perhaps create a fallback if https fails to then try http.
Thanks for the feedback! Citrix Hypervisor 8 seems to have some odd things happening in it, alas, and I'm sorry I have not had the time to thoroughly test the script out yet in that newer environment.

**Comment by NAUbackup** [comment]
Does including ssl near the top and changing the code to read

        ignore_ssl=True
        session = XenAPI.Session('https://localhost/')

still not work?

**Comment by sniperkitten** [comment]
Hi

Added this line to VmBackup.py and got same error, so returned to http
protocol

**Comment by leyvidaniel** [comment]
i have the same error too, i started to try the scripts yesterday on the citrix 8.0, only works with http protocol

**Comment by NAUbackup** [comment]
Try substituting that call with the following expanded code:

    # acquire a xapi session by logging in
    try:
        username = 'root'
        ignore_ssl=True
        # try SSL connection
        session = XenAPI.Session('https://localhost/')
        #print "session is: %s " % session
        if session != "<ServerProxy for localhost/>":
           # fall back to plain http
           session = XenAPI.Session('http://localhost/')

        session.xenapi.login_with_password(username, password)

**Comment by LinKJeTT** [comment]
i'm sorry but what lines should I replace?

**Comment by NAUbackup** [comment]
Put that in place of the lines:
 try:
        username = 'root'
        session = XenAPI.Session('https://localhost/')
        session.xenapi.login_with_password(username, password)
        hosts = session.xenapi.host.get_all()

**Comment by sniperkitten** [comment]
Hi

Tried extended code, still same error
Though I'm new to python and not very reliable tester - had IndentationErrors initially)

Regards,
Alex

**Comment by NAUbackup** [comment]
Thank you, Alex, for the feedback. It runs fine as such under 7.1. I will take another look. I really need to get an instance up and running on my 8.0 test pool. I'd have done so sooner except I have to get the NFS networking sorted out.
--Tobias

**Comment by dangbird** [comment]
If you would like I have 8.0 fully patched on a box, with a tiny VM that backs up in a few seconds, mounted to NFS that I can IP Gate to your IP via SSH.  Happy to let you play with the script on this as some small way of saying thank-you for all the efforts...  Not a problem if you would like let me know.

**Comment by NAUbackup** [comment]
Thank you, Dan, I will keep that in mind if I cannot get something rigged up here soon. Your offer is much appreciated!
