### ISSUE TITLE
ImportError: No module named six.moves.xmlrpc_client

### ISSUE THREAD

**Issue by bmssas** [NAUbackup/VmBackup#70]
ciao, ho 1 pool di 2 host con xenserver 7.0
quando provo ad eseguire ./VmBackup.py vedo l'errore 

Traceback (most recent call last):
  File "./VmBackup.py", line 68, in <module>
    import sys, time, os, datetime, subprocess, re, shutil, XenAPI, smtplib, re, base64, socket
  File "/snapshot/NAUbackup/XenAPI.py", line 58, in <module>
    import six.moves.xmlrpc_client as xmlrpclib
ImportError: No module named six.moves.xmlrpc_client

potete aiutarmi?

grazie in anticipo

**Comment by NAUbackup** [comment]
Could you please show me what your full command line looks like?
Did you install the latest python module according to the installation instructions?

Ciao!

**Comment by bmssas** [comment]
hi any command returns the same error.
how to install the latest python module?
can you help me?
thank you

**Comment by NAUbackup** [comment]
It is explained step 6 in the README file:
Install the XenServer Software Development Kit from www.citrix.com/downloads - download the XenServer and copy file XenAPI.py into the same directory where VmBackup.py exists.

    To verfy XenApi, execute VmBackup with a valid password and some simple vm-name.
    Example: ./VmBackup.py password vm-name preview
    Note: if password has any special characters, then escape with back slash:
    ./VmBackup.py pass$word vm-name

**Comment by bmssas** [comment]
hi, what is the procedure to install sdk? I downloaded sdk and copied the xenapi.py file into the same directory as Vmbackup.py
Do I have to do anything else?

**Comment by NAUbackup** [comment]
I believe that is all. Make sure it has read and possibly also execute privileges set. If you run "ls -l XenApi.py" there should be at least an "r" that shows up on the permissions. I'm not at a point where I can conveniently check directly what the exact permission settings are, but try running VmBackup.py now.
