### ISSUE TITLE
VmBackup problem with export vm 

### ISSUE THREAD

**Issue by prezesihno** [NAUbackup/VmBackup#87]
Hello,

im interested in this script, it is going to be great for my purposes, but I cant get it to work :(
Something in my configuration is wrong.
I would be grateful for help.
I have XenServer 7.0 and configuration is default (like python) and Im only trying to test script with easiest possible command like: 
 ./VmBackup.py password vm-name

2018-10-08-(20:55:05) - VmBackup config loaded from: XOA
2018-10-08-(20:55:05) - VmBackup.py running with these settings:
2018-10-08-(20:55:05) -   backup_dir        = /snapshots/BACKUPS
2018-10-08-(20:55:05) -   status_log        = /snapshots/NAUbackup/status.log
2018-10-08-(20:55:05) -   compress          = False
2018-10-08-(20:55:05) -   max_backups       = 4
2018-10-08-(20:55:05) -   vdi_export_format = raw
2018-10-08-(20:55:05) -   pool_db_backup    = 0
2018-10-08-(20:55:05) -   exclude (cnt)= 0
2018-10-08-(20:55:05) -   exclude:
2018-10-08-(20:55:05) -   vdi-export (cnt)= 0
2018-10-08-(20:55:05) -   vdi-export:
2018-10-08-(20:55:05) -   vm-export (cnt)= 1
2018-10-08-(20:55:05) -   vm-export: XOA
['HOST_IS_SLAVE', '192.168.2.19']
2018-10-08-(20:55:05) - SUCCESS check of parameters
2018-10-08-(20:55:05) - ===========================
2018-10-08-(20:55:05) - VmBackup running on xenserver2 ...
2018-10-08-(20:55:05) - ===========================
2018-10-08-(20:55:05) - Check if backup directory /snapshots/BACKUPS is writable ...
2018-10-08-(20:55:05) - /bin/touch "/snapshots/BACKUPS/00VMbackupWriteTest"
2018-10-08-(20:55:05) - Success: backup directory area is writable
2018-10-08-(20:55:05) - ===========================
2018-10-08-(20:55:05) - Space before backups: df -Th /snapshots/BACKUPS
2018-10-08-(20:55:05) - Filesystem     Type  Size  Used Avail Use% Mounted on
2018-10-08-(20:55:05) - /dev/sda1      ext3   18G  1.8G   16G  11% /
2018-10-08-(20:55:05) - ************ vdi-export= ***************
2018-10-08-(20:55:05) - ************ vm-export= ***************
2018-10-08-(20:55:05) - *** vm-export begin XOA
2018-10-08-(20:55:05) - vm-export - vm_name: XOA max_backups: 4
2018-10-08-(20:55:05) - new backup_dir: /snapshots/BACKUPS/XOA/backup-2018-10-08-(20:55:05)
unconverted data remains: Z
2018-10-08-(20:55:05) - ***ERROR EXCEPTION - <type 'exceptions.ValueError'>
2018-10-08-(20:55:05) - ***ERROR NOTE: see VmBackup output for details
Traceback (most recent call last):
  File "./VmBackup.py", line 1495, in <module>
    main(session)
  File "./VmBackup.py", line 347, in main
    vm_meta_status = gather_vm_meta(vm_object, full_backup_dir)
  File "./VmBackup.py", line 569, in gather_vm_meta
    vm_record = session.xenapi.VM.get_record(vm_object)
  File "/root/xen-backup/XenAPI.py", line 231, in __call__
    return self.__send(self.__name, args)
  File "/root/xen-backup/XenAPI.py", line 135, in xenapi_request
    result = _parse_result(getattr(self, methodname)(*full_params))
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1476, in parse_response
    p.feed(data)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 558, in feed
    self._parser.Parse(data, 0)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 824, in end
    return f(self, join(self._data, ""))
  File "/usr/lib64/python2.7/xmlrpclib.py", line 907, in end_dateTime
    value = _datetime_type(data)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 468, in _datetime_type
    t = time.strptime(data, "%Y%m%dT%H:%M:%S")
  File "/usr/lib64/python2.7/_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib64/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])

I veryfied description of my vm, and everything I could. Unfortunately I cant find solution.

Thank You in advance for any tips.

**Comment by NAUbackup** [comment]
Did you try running with the "preview" option to look for any possible configuration errors?

--Tobias
